LABEL dev="dipak"

RUN apt-get update && \
    apt-get install -y wget unzip openjdk-11-jdk

ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.118/bin/apache-tomcat-9.0.118.zip /opt
RUN unzip /opt/apache-tomcat-9.0.118.zip -d /opt

WORKDIR /opt/apache-tomcat-9.0.118/
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war /opt/apache-tomcat-9.0.118/webapps/
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar /opt/apache-tomcat-9.0.118/lib/mysql-connector.jar
COPY context.xml /opt/apache-tomcat-9.0.118/conf/context.xml

RUN chmod +rwx /opt/apache-tomcat-9.0.118/bin/*.sh

CMD ["/opt/apache-tomcat-9.0.118/bin/catalina.sh", "run"]

EXPOSE 8080
