services:
  tomcatwebserver:
    build: .
    ports:
      - "8080:8080"
    container_name: tomcatwebserver

  tomcatwebserveremp:
    build: .
    ports:
      - "81:8080"
    container_name: tomcatwebserveremp
